/**
 * Lectura centralizada de variables de entorno públicas (web).
 * Prefijo estándar: NEXT_PUBLIC_
 * Fallback legacy: SIGUIENTE_* (migración desde Vercel)
 */

const LEGACY_ALIASES: Record<string, string[]> = {
  NEXT_PUBLIC_SITE_URL: ["SIGUIENTE_URL_SITIO", "SIGUIENTE_SITE_URL"],
  NEXT_PUBLIC_MONETAG_ZONE_ID: [
    "SIGUIENTE_ID_ZONA_MONETAG",
    "SIGUIENTE_MONETAG_ZONE_ID",
    "SIGUIENTE_ZONE_ID_MONETAG",
  ],
  NEXT_PUBLIC_MONETAG_SCRIPT_SRC: [
    "SIGUIENTE_SCRIPT_MONETAG",
    "SIGUIENTE_MONETAG_SCRIPT_SRC",
  ],
  NEXT_PUBLIC_MONETAG_DIRECT_LINK: [
    "SIGUIENTE_ENLACE_DIRECTO_DE_MONETAG",
    "SIGUIENTE_ENLACE_DIRECTO_DE_MONETAG_I",
    "SIGUIENTE_ENLACE_DIRECTO_MONETAG",
    "SIGUIENTE_MONETAG_DIRECT_LINK",
  ],
  NEXT_PUBLIC_MONETAG_DIRECT_LINK_ZONE: [
    "SIGUIENTE_ID_ENLACE_DIRECTO_MONETAG",
    "SIGUIENTE_MONETAG_DIRECT_LINK_ZONE",
  ],
  NEXT_PUBLIC_MONETAG_INVOKE_SCRIPT: [
    "SIGUIENTE_MONETAG_INVOKE_SCRIPT",
    "SIGUIENTE_SCRIPT_INVOKE_MONETAG",
  ],
  NEXT_PUBLIC_MONETAG_SCRIPT_IPP: [
    "SIGUIENTE_MONETAG_SCRIPT_IPP",
    "SIGUIENTE_SCRIPT_IPP_MONETAG",
  ],
  NEXT_PUBLIC_MONETAG_ZONE_BANNER: [
    "SIGUIENTE_MONETAG_ZONE_BANNER",
    "SIGUIENTE_ZONA_BANNER_MONETAG",
  ],
  NEXT_PUBLIC_MONETAG_ZONE_HOME_TOP: ["SIGUIENTE_ZONA_HOME_TOP"],
  NEXT_PUBLIC_MONETAG_ZONE_HOME_MID: ["SIGUIENTE_ZONA_HOME_MID"],
  NEXT_PUBLIC_MONETAG_ZONE_HOME_FEATURE: ["SIGUIENTE_ZONA_HOME_FEATURE"],
  NEXT_PUBLIC_MONETAG_ZONE_HOME_BOTTOM: ["SIGUIENTE_ZONA_HOME_BOTTOM"],
  NEXT_PUBLIC_MONETAG_ZONE_DEPORTES: ["SIGUIENTE_ZONA_DEPORTES"],
  NEXT_PUBLIC_MONETAG_ZONE_DEPORTES_TOP: ["SIGUIENTE_ZONA_DEPORTES_TOP"],
  NEXT_PUBLIC_MONETAG_ZONE_DEPORTES_MID: ["SIGUIENTE_ZONA_DEPORTES_MID"],
  NEXT_PUBLIC_MONETAG_ZONE_CATALOG: ["SIGUIENTE_ZONA_CATALOG"],
  NEXT_PUBLIC_MONETAG_ZONE_ENVIVO: ["SIGUIENTE_ZONA_ENVIVO"],
  NEXT_PUBLIC_MONETAG_ZONE_PLAYER: ["SIGUIENTE_ZONA_PLAYER"],
  NEXT_PUBLIC_MONETAG_ZONE_ADGATE_TOP: ["SIGUIENTE_ZONA_ADGATE_TOP"],
  NEXT_PUBLIC_MONETAG_ZONE_ADGATE_MID: ["SIGUIENTE_ZONA_ADGATE_MID"],
  NEXT_PUBLIC_MONETAG_ZONE_ADGATE_BOTTOM: ["SIGUIENTE_ZONA_ADGATE_BOTTOM"],
  NEXT_PUBLIC_MONETAG_ZONE_PREROLL: ["SIGUIENTE_ZONA_PREROLL"],
  NEXT_PUBLIC_ANDROID_APK_URL: [
    "SIGUIENTE_URL_APK_PUBLICA_ANDROID",
    "SIGUIENTE_URL_APK_PUBLICA_ANDROI",
    "SIGUIENTE_APK_ANDROID_URL",
  ],
  NEXT_PUBLIC_IOS_APP_URL: [
    "SIGUIENTE_URL_IOS",
    "SIGUIENTE_IOS_APP_URL",
  ],
};

/** Lee env con prefijo NEXT_PUBLIC_ (fallback a SIGUIENTE_ legacy). */
export function getPublicEnv(key: string): string {
  const primary = process.env[key]?.trim();
  if (primary) return primary;

  for (const legacy of LEGACY_ALIASES[key] ?? []) {
    const value = process.env[legacy]?.trim();
    if (value) return value;
  }

  return "";
}

/** Alias corto para múltiples candidatos del mismo slot. */
export function getPublicEnvFirst(...keys: string[]): string {
  for (const key of keys) {
    const value = getPublicEnv(key);
    if (value) return value;
  }
  return "";
}
